name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Mac binary
        run: GOOS=darwin GOARCH=amd64 go build -o dist/mac/SyncApp .

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -o dist/windows/SyncApp.exe .

      - name: Create Mac zip
        run: zip -r CalSync-mac-${{ github.ref_name }}.zip dist/mac/

      - name: Create Windows zip
        run: zip -r CalSync-windows-${{ github.ref_name }}.zip dist/windows/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CalSync-mac-${{ github.ref_name }}.zip
            CalSync-windows-${{ github.ref_name }}.zip
          generate_release_notes: true
